# Generated by Django 4.2.2 on 2023-06-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generos', '0002_rename_generos_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
                ('anhio', models.IntegerField()),
                ('director', models.CharField(max_length=128)),
                ('generos', models.ManyToManyField(to='generos.genero')),
            ],
        ),
    ]
