# Generated by Django 4.2.2 on 2023-06-08 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelicula',
            options={'ordering': ['titulo', 'anhio', 'director']},
        ),
    ]
