# Generated by Django 4.2.2 on 2023-06-06 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='generos',
            new_name='Genero',
        ),
    ]
